# When a release page is published, start the release artifact process
on:
 push:
  tags:
  - '*'
name: Build, Test, and Publish kata-deploy

jobs:
  # create image and upload to release page (can we get branch information from release tag?
  publish-artifacts:
    runs-on: ubuntu-latest
    steps:
    - name : the ok ok 
      run: |  
        echo "hello worold"
        sudo apt-get update
        sudo apt-get install -y flex
        echo "still?"
        # for test development:
        echo "go path:" 
        export GOPATH=$HOME/go
        go get github.com/egernst/packaging-1 || true
        cd $GOPATH/src/github.com/egernst/packaging-1/release

        tag=`echo $GITHUB_REF | cut -d/ -f3-`
        echo `pwd`
        echo `ls`

        bash -x ./build-artifacts.sh $tag

        echo "done...."
