on: push

name: Build, Test, and Publish kata-deploy

jobs:
  kata-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: build-and-push-kata-deploy-ci
        run: |
          git clone https://github.com/amshinde/kata-packaging
          docker build --build-arg KATA_VER=1.9.0-rc0 -t katadocker/kata-deploy-ci:${{ github.sha }} ./kata-packaging/kata-deploy
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push katadocker/kata-deploy-ci:${{ github.sha }}
