on: push

name: Build, Test, and Publish kata-deploy

jobs:
  kata-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get-kata-deploy-dockerfile-env
        run: |
          git clone https://github.com/amshinde/kata-packaging
      - name: build-kata-deploy-for-test
        uses: actions/docker/cli@master
        with:
          args: build --build-arg KATA_VER=1.9.0-rc0 -t katadocker/kata-deploy-ci:${{ github.sha }} ./kata-packaging/kata-deploy
      - name: docker-login
        uses: actions/docker/login@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: docker-push-kata-deploy-ci
        uses: actions/docker/cli@master
        with:
          args: push katadocker/kata-deploy-ci:${{ github.sha }}
