
# When a release page is published, start the release artifact process
on: push

name: Build, Test, and Publish kata-deploy

env:
  build_image=false
  build_kata_components=false
  build_kernel_experimental=false
  build_kernel=false

jobs:
  # This first stage will return a list of kata-artifacts which 
  # should be built as parallel jobs
  get-artifact-list:
    runs-on: ubuntu-latest
    steps:
    - name: get-list
      run: |
        echo ::set-env name=build_image::true;

              
    - name: set-workflow-vars
      
  build_image:
    needs: get-artifact-list
    if: build_image
    runs-on: ubuntu-latest
    steps:
    - name: run-build-image
      run: | 
         echo "called build image"

  build_kata_components:
    needs: get-artifact-list
    if: build_kata_components
    runs-on: ubuntu-latest
    steps:
    - name: run-build-kata-components
      run: | 
         echo "called build kata components

    
