on: push

jobs:
  get-artifact-list:
    runs-on: ubuntu-latest
    steps:
      - name: get the list
        run: |
         build_image="bar"
         echo "the build image: ${build_image}" 
         echo "foobar" > artifact-list.txt
         cat artifact-list.txt
      - name: dump my global variable
        uses: actions/upload-artifact@master
        with: 
          name: artifact-list 
          path: artifact-list.txt
  one:
    runs-on: ubuntu-16.04
    needs: get-artifact-list
    steps:
      - name: get my global variable
        uses: actions/download-artifact@master
        with:
          name: artifact-list
      - name: oooooh god please work
        run: |
         value=$(cat artifact-list/artifact-list.txt)
         echo "::set-env name=build_image::$value"
         echo "$build_image"
      - name: predicated-attempt
        if: $build_image == "foobar"
        run: |
                echo "my variable: $build_image"

